#!/usr/bin/env python3
"""Generate a docker-compose.yml with N redroid Android instances plus a
ws-scrcpy web viewer (device list + a live screen per device) in the browser.

Usage:
    python3 scripts/gen_compose.py --count 4 --android 11.0.0

Then:
    docker compose up -d
    ./scripts/connect.sh      # register each Android with the viewer
    open http://localhost:8000
"""
import argparse

HEADER = """# ─────────────────────────────────────────────────────────────
# GENERATED by scripts/gen_compose.py — edit that script, not this file.
# A grid of independent Android instances (redroid) + a web panel viewer
# (ws-scrcpy). View everything at http://localhost:8000
# ─────────────────────────────────────────────────────────────
services:
"""

REDROID_TMPL = """  android-{i}:
    image: {image}
    container_name: redroid-{i}
    privileged: true
    # Each instance gets its own ADB port on the host: 5555, 5556, ...
    ports:
      - "{adb_port}:5555"
    volumes:
      - ./data/android-{i}:/data
    command:
      - androidboot.redroid_width={width}
      - androidboot.redroid_height={height}
      - androidboot.redroid_dpi={dpi}
      - androidboot.redroid_fps=30
      # GPU is off by default for portability; flip to host for speed if your
      # host has a GPU + drivers passed through.
      - androidboot.redroid_gpu_mode=guest
    restart: unless-stopped
"""

VIEWER_TMPL = """  viewer:
    build: ./ws-scrcpy
    container_name: ws-scrcpy
    ports:
      - "{port}:8000"
    # The viewer adb-connects to each redroid instance over the internal
    # docker network (service name : internal port 5555).
    environment:
      DEVICES: "{devices}"
    healthcheck:
      # node is already in the image; avoids needing curl/wget.
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8000',r=>process.exit(r.statusCode<500?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    depends_on:
{deps}
    restart: unless-stopped
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--count", type=int, default=4, help="number of Android panels")
    p.add_argument("--android", default="11.0.0", help="redroid Android version (e.g. 11.0.0, 12.0.0, 13.0.0)")
    p.add_argument("--width", type=int, default=720)
    p.add_argument("--height", type=int, default=1280)
    p.add_argument("--dpi", type=int, default=320)
    p.add_argument("--port", type=int, default=8000, help="host port for the web viewer")
    p.add_argument("-o", "--out", default="docker-compose.yml")
    args = p.parse_args()

    # redroid's official images do NOT bundle Google Play / GApps — install
    # those into a running instance afterwards (see README). Verify the tag at
    # https://hub.docker.com/r/redroid/redroid/tags
    image = f"redroid/redroid:{args.android}-latest"

    blocks = [HEADER]
    deps = []
    devices = []
    for i in range(1, args.count + 1):
        blocks.append(
            REDROID_TMPL.format(
                i=i,
                image=image,
                adb_port=5554 + i,  # -> 5555, 5556, ... (host-side, for manual adb)
                width=args.width,
                height=args.height,
                dpi=args.dpi,
            )
        )
        deps.append(f"      - android-{i}")
        devices.append(f"android-{i}:5555")  # internal docker-network address
    blocks.append(VIEWER_TMPL.format(deps="\n".join(deps), devices=" ".join(devices), port=args.port))

    with open(args.out, "w") as f:
        f.write("\n".join(blocks))
    print(f"Wrote {args.out} with {args.count} Android panel(s) (image: {image}).")
    print("Next: docker compose up -d   then open http://localhost:8000")


if __name__ == "__main__":
    main()
